updates to handle terminal erro messages

diff --git a/modules/test/base/bin/setup b/modules/test/base/bin/setup
--- a/modules/test/base/bin/setup
+++ b/modules/test/base/bin/setup
@@ -23,17 +23,27 @@ export BIN_DIR="/testrun/bin"
 # Default interface should be veth0 for all containers
 export IFACE=veth0
 
+# Assign the current host user
+export HOST_USER=$(whoami)
+
 # Create a local user that matches the same as the host
 # to be used for correct file ownership for various logs
-# HOST_USER mapped in via docker container environemnt variables
-useradd $HOST_USER
+# HOST_USER mapped in via docker container environment variables
+if ! id "$HOST_USER" &>/dev/null; then
+    useradd "$HOST_USER"
+else
+    echo User $HOST_USER already exists
+fi
+
+# Create the output directory
+mkdir -p "$OUTPUT_DIR"
 
 # Set permissions on the output files
 chown -R $HOST_USER $OUTPUT_DIR
 
 # Enable IPv6 for all containers
 sysctl net.ipv6.conf.all.disable_ipv6=0
-sysctl -p
+sysctl -p || echo "Failed to apply the settings" 
 
 # Read in the config file
 CONF_FILE="/testrun/conf/module_config.json"
